version: "3"

services:
  mongodb:
    image: mongo:4.4.11-rc0-focal
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=miniclip
      - MONGO_INITDB_USER=miniclip
      - MONGO_INITDB_PWD=miniclip123
      - MONGODB_DATABASE=miniclip
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet
    tty: true
    restart: always
    # command: mongod

  app:
    image: node
    working_dir: /home/node/app
    links:
      - mongodb
    depends_on:
      - mongodb
    command: "npm run start:debug"
    ports:
      - 3010:3010
      - 9229:9229
    tty: true
    restart: unless-stopped
    volumes:
      - .:/home/node/app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge