version: "3"

services:
  app:
    image: node
    working_dir: /home/node/app
    links:
      - mongodb
    depends_on:
      - mongodb
    command: "npm run start:debug"
    ports:
      - 3010:3010
      - 9229:9229
    tty: true
    restart: unless-stopped
    volumes:
      - .:/home/node/app
    networks:
      - webnet

networks:
  webnet:
    driver: bridge