version: "3"

services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootadmin123
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - vpcbr
    restart: always
    command: mongod

  app:
    image: node
    working_dir: /home/node/app
    links:
      - mongodb
    depends_on:
      - mongodb
    command: "npm run start:debug"
    ports:
      - 3010:3010
      - 9229:9229
    tty: true
    restart: unless-stopped
    volumes:
      - .:/home/node/app
    networks:
      vpcbr:
        ipv4_address: 172.44.9.3

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.9.0/24
